backend:
  mode: skyway2023
  url: https://udonarium-backend.yutarou02.workers.dev #Your Backend API URL

webrtc:
  key: aaaaaaaa-bbbb-ccccc-dddd-eeeeeeeeeeee  #Your SkyWay API key
app: #未使用
dice: #未使用

